version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flask:
    build: .
    container_name: todo_api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - mysql
    restart: always
    environment:
      FLASK_APP: ${FLASK_APP}
      FLASK_RUN_HOST: ${FLASK_RUN_HOST}
      DB_HOST: mysql_container
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DATA: ${DB_DATA}

volumes:
  mysql_data:
